//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veget.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int idOrder { get; set; }
        public int ProdId { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateSale { get; set; }
        public int caunt { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Products Products { get; set; }
    }
}
