//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veget.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int idProd { get; set; }
        public string Title { get; set; }
        public byte[] Image { get; set; }
        public int CatId { get; set; }
        public int Price { get; set; }
        public int SalId { get; set; }
        public Nullable<System.DateTime> DateCrete { get; set; }
        public Nullable<System.DateTime> DateDie { get; set; }
        public int caunt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual SAL SAL { get; set; }
        public virtual Cat Cat { get; set; }
    }
}
