//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veget.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocks
    {
        public int idStocks { get; set; }
        public string Title { get; set; }
        public int idSal { get; set; }
        public int ImportersId { get; set; }
    
        public virtual Importers Importers { get; set; }
        public virtual SAL SAL { get; set; }
    }
}
